name: High-Spec RDP Setup

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'URL for downloading Portmap Configuration:'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        
    - name: Install Latest Software
      run: |
        choco install openvpn git python visualstudio2019community docker-desktop -y
      
    - name: Download Portmap Configuration
      run: |
        $inputUrl = "${{ github.event.inputs.portmap_config_url }}"
        $fileName = [System.IO.Path]::GetFileName($inputUrl)
        $newUrl = "https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        Invoke-WebRequest -Uri $newUrl -OutFile "C:\portmap.ovpn"
        
    - name: Enable Remote Desktop
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      
    - name: Set RDP Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Create Admin User with High Specs
      run: |
        if (-not (Get-LocalUser -Name "HighSpecAdmin" -ErrorAction SilentlyContinue)) {
          New-LocalUser -Name "HighSpecAdmin" -Password (ConvertTo-SecureString -AsPlainText "YourStrongPassword!" -Force) -FullName "High Spec Admin" -Description "Administrator Account"
          Add-LocalGroupMember -Group "Administrators" -Member "HighSpecAdmin"
        }

    - name: Change RDP Port to 4000
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "PortNumber" -Value 4000
        New-NetFirewallRule -DisplayName "RDP Port 4000" -Direction Inbound -Protocol TCP -LocalPort 4000 -Action Allow

    - name: Restart Remote Desktop Service
      run: Restart-Service -Name "TermService" -Force

    - name: Start OpenVPN
      run: |
        Start-Process -NoNewWindow -FilePath "C:\Program Files\OpenVPN\bin\openvpn.exe" -ArgumentList "--config C:\portmap.ovpn" -Wait
        
    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
